[package]
name = "wkhtmltopdf"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]

[dependencies]
wkhtmltox-sys = "0.1.0"
url = "1.1.1"
lazy_static = "0.2.1"
log = "0.3"
quick-error = "1.1.0"
thread-id = "2.0.0"

[dev-dependencies]
env_logger = "0.3"