[package]
name = "wkhtmltopdf"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]

[dependencies]
libwkhtmltox-sys = { git = "https://github.com/anowell/libwkhtmltox-sys.git" }
url = "1.1.1"
lazy_static = "0.2.1"